# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="ashishbansal689@gmail.com"

# Add a volume pointing to /tmp
VOLUME /home/decimal/tmp

# Make port 9001 available to the world outside this container
EXPOSE 9001

# The application's jar file
ARG JAR_FILE=target/create-docker-1.0.jar

# Add the application's jar to the container
ADD ${JAR_FILE} docker.jar

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/docker.jar"]
